name: webviewx_plus
description: A cross-platform webview using webview_flutter for
  mobile and iFrame for web.
repository: https://github.com/Mahad61/webviewx_plus
version: 0.3.2

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.8.2
  pointer_interceptor: ^0.9.3+3
  uuid: ^3.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

